version: "3.8"

services:
  mongo:
    image: mongo:6.0.4-focal
    container_name: crowbar-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: "crowbar"
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: crowbartools
    ports:
      - 127.0.0.1:27017-27019:27017-27019
    volumes:
      - cbDbData:/data/db
      - cbDbConfig:/data/configdb
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: crowbartools
      ME_CONFIG_MONGODB_URL: mongodb://admin:crowbartools@mongo:27017/

volumes:
  cbDbData:
  cbDbConfig:
